baseurl = "http://andriydruk.github.io/"
languageCode = "en-us"
title = "Yet Another Android Developer Blog"
theme = "startbootstrap-clean-blog"

canonifyurls = true
paginate = 10
copyright = "Code released under the Apache 2.0 license."

disqusShortname = "yetanotherandroiddeveloperblog"

[author]
  name = "Andriy Druk"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Andriy Druk"
  Author = "Andriy Druk"
  email = "andriy.druk@gmail.com"
  Ganalytics = "UA-67278568-1"

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/AndriyDruk"
[[params.social]]
  title = "github"
  url = "https://github.com/andriydruk"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180