baseurl = "https://www.andriydruk.com"
languageCode = "en-us"
title = "Yet Another Android Developer Blog"
theme = "min-blog"

metadataformat = "yaml"
canonifyurls = true
paginate = 10
copyright = "Code released under the Apache 2.0 license."

disqusShortname = "yetanotherandroiddeveloperblog"

[author]
  name = "Andriy Druk"

[params]
  DateForm = "Jan 2, 2006"
  Description = "Projects • Github • Twitter • About"
  Author = "Andriy Druk"
  email = "andriy.druk@gmail.com"
  Ganalytics = "UA-67278568-1"
  logo = "img/logo.png"
  Position = "Software Mobile Engineer"
  twitter = "AndriyDruk"
  github  = "andriydruk"
  linkedin = "andriy-druk-23147344"